title: Brady Miller
logo: /assets/img/headshot.png
description: IT Student Who Is Interested in Networking and System/Database Administration. Currently Studying for CompTIA Network+.
show_downloads: true
theme: jekyll-theme-minimal
