title: Brady Miller
logo: /assets/img/UpdatedHeadshot.jpg
description: Network Engineer with a background in network planning, configuration, and troubleshooting. Highly focused on advancing skills in networking, advanced and scalable configurations, and problem solving.
show_downloads: true
theme: jekyll-theme-minimal
