title: Brady Miller
logo: /assets/img/UpdatedHeadshot.jpg
description: Network Engineer with a focus on building skills in networking, advanced configuration, and problem solving.
show_downloads: true
theme: jekyll-theme-minimal
