title: Brady Miller
logo: /assets/img/headshot.png
description: Aspiring Data Analyst Who Enjoys Drawing Insights From Data Using Tools Such as SQL and Tableau
show_downloads: true
theme: jekyll-theme-minimal
