title: Brady Miller
logo: /assets/img/UpdatedHeadshot.jpg
description: Aspiring Network Engineer/Admin with a focus on building skills in networking, information security, and problem solving.
show_downloads: true
theme: jekyll-theme-minimal
